# Generated by Django 3.0.3 on 2020-02-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='a',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
