# Generated by Django 3.0.3 on 2020-02-11 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_demo', '0002_user_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='a',
        ),
    ]
