# Generated by Django 3.0.3 on 2020-03-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_demo', '0003_remove_user_a'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgname', models.CharField(max_length=50)),
                ('imgurl', models.FileField(upload_to='img/')),
            ],
        ),
    ]
