# Generated by Django 2.2.8 on 2020-05-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_demo', '0007_auto_20200515_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpro',
            name='sms',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
